lang: ko-KR
timezone: Asia/Seoul
title: mye785C83 
author: mye785C83
github:
  username: mye785C83
  url: 'https://github.com/mye785C83'

# baseurl: '/mye785c83.github.io'
permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  categories:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/
      toc: true         # Display TOC column in posts.
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "categories"             # see `site.collections`
    values:
      layout: "default"
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false