lang: ko-KR
timezone: Asia/Seoul
title: mye785C83 
author: mye785C83

baseurl: '/mye785c83.github.io'

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json